name: pi-snm-qde
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.8.1
  - astor=0.8.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - c-ares=1.15.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - cpuonly=1.0
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.2
  - glib=2.63.1
  - gmp=6.1.2
  - google-pasta=0.1.8
  - grpcio=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.2
  - jinja2=2.10.3
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=5.2.0
  - jupyter_core=4.6.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - notebook=6.0.2
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - openssl=1.1.1d
  - opt_einsum=3.1.0
  - packaging=20.0
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=19.3.1
  - pluggy=0.13.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - protobuf=3.11.2
  - ptyprocess=0.6.0
  - py=1.8.1
  - pycparser=2.19
  - pygments=2.5.2
  - pymongo=3.9.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - pytest=5.3.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=1.3.1
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - readline=7.0
  - scikit-learn=0.22
  - scipy=1.3.2
  - send2trash=1.5.0
  - setuptools=44.0.0
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - tabulate=0.8.3
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - torchvision=0.4.2
  - tornado=6.0.3
  - traitlets=4.3.3
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - alembic==1.3.2
    - cliff==2.17.0
    - cmd2==0.9.22
    - colorama==0.4.3
    - colorlog==4.1.0
    - docopt==0.6.2
    - fastcache==1.1.0
    - jax==0.1.56
    - jaxlib==0.1.37
    - jsonpickle==0.9.6
    - mako==1.0.7
    - munch==2.5.0
    - optuna==0.19.0
    - pbr==5.4.4
    - prettytable==0.7.2
    - py-cpuinfo==5.0.0
    - pyperclip==1.7.0
    - python-editor==1.0.4
    - pyyaml==5.3
    - sacred==0.7.5
    - sqlalchemy==1.3.12
    - stevedore==1.31.0
    - tqdm==4.41.1
    - typing==3.7.4.1
    - wcwidth==0.1.8
